receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  googlecloud:
    log:
      default_log_name: opentelemetry.io/collector-exported-log
  debug:
    verbosity: detailed
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20
  resource_detection:
    detectors: [gcp]
    timeout: 10s
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter]
      exporters: [googlecloud]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter]
      exporters: [googlecloud]
    logs:
      receivers: [otlp]
      processors: [memory_limiter]
      exporters: [googlecloud]